version: "3.3"

services:
  noteskube:
    build: ./noteskube
    container_name: noteskube
    ports:
      - "3000:80"
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root  # 👈 REQUIRED to access docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 REQUIRED so Jenkins can run Docker commands
    restart: always

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "81:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  jenkins_data:
  grafana_data:
